[package]
name = "solve99game-rs"
version = "0.1.0"
authors = ["Ben Wiederhake <BenWiederhake.GitHub@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static_assert_macro = "1.0.0"
openssl = "0.10.25"
